# Mount volume data folder warez to a drive with games
# Mount volume 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    image: kapitanczarnobrod/sharewarez:latest
    ports:
      - "5001:5001"
    environment:
      - APP_USERNAME=${SHAREWAREZ_USERNAME}
      - APP_PASSWORD=${SHAREWAREZ_PASSWORD}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - WAIT_HOSTS="db:5432"
    volumes:
      - "${DATA_FOLDER_WAREZ}:/"
      - "${UPLOAD_FOLDER}:/app/modules/static/library/"
    depends_on:
      - db     

  db:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
       - ./db_data:/var/lib/postgresql/data/pgdata
